@echo off
rem ---------------------------------------------------------------------------
rem Compile windows/runner/shaders/nv12_to_bgra.hlsl into DXBC bytecode headers.
rem
rem Why offline (instead of runtime D3DCompile):
rem   1) no runtime dependency on d3dcompiler_47.dll, and no compile cost during
rem      the decoder create phase;
rem   2) the generated bytecode is committed, so the artifact is deterministic and
rem      reviewable (diffable) across machines and SDK versions.
rem Outputs (regenerate after every shader change):
rem   windows/runner/shaders/generated/vs_nv12_to_bgra.h
rem   windows/runner/shaders/generated/ps_nv12_to_bgra.h
rem
rem Usage: tools\build_shader.cmd
rem
rem NOTE: this file is intentionally ASCII-only. cmd.exe reads .cmd files with the
rem system code page (936 here), and UTF-8 Chinese comments get mangled into stray
rem backslashes/quotes that break the script.
rem ---------------------------------------------------------------------------
setlocal EnableExtensions

set "REPO=%~dp0.."
set "SRC=%REPO%\windows\runner\shaders\nv12_to_bgra.hlsl"
set "OUTDIR=%REPO%\windows\runner\shaders\generated"

set "FXC="
for /f "delims=" %%i in ('where fxc.exe 2^>nul') do if not defined FXC set "FXC=%%i"
if not defined FXC (
  rem Newest SDK version first (/o-n), then pick its x64 fxc.
  for /f "delims=" %%v in ('dir /b /ad /o-n "C:\Program Files (x86)\Windows Kits\10\bin\10.*" 2^>nul') do (
    if not defined FXC if exist "C:\Program Files (x86)\Windows Kits\10\bin\%%v\x64\fxc.exe" set "FXC=C:\Program Files (x86)\Windows Kits\10\bin\%%v\x64\fxc.exe"
  )
)
if not defined FXC (
  echo [build_shader] fxc.exe not found: install the Windows SDK or add fxc.exe to PATH.
  exit /b 1
)
echo [build_shader] fxc=%FXC%

if not exist "%OUTDIR%" mkdir "%OUTDIR%"

"%FXC%" /nologo /T vs_4_0 /E VSMain /O3 /Fh "%OUTDIR%\vs_nv12_to_bgra.h" /Vn g_nv12_to_bgra_vs_bytecode "%SRC%"
if errorlevel 1 exit /b 1
"%FXC%" /nologo /T ps_4_0 /E PSMain /O3 /Fh "%OUTDIR%\ps_nv12_to_bgra.h" /Vn g_nv12_to_bgra_ps_bytecode "%SRC%"
if errorlevel 1 exit /b 1

echo [build_shader] done:
echo   %OUTDIR%\vs_nv12_to_bgra.h
echo   %OUTDIR%\ps_nv12_to_bgra.h
exit /b 0
